#!/bin/bash
( 
echo 'audio feed ctr isaudio 1'
/usr/local/bin/gst-launch-1.0 -q alsasrc device=hw:2,0 ! queue ! audioresample ! audioconvert ! audio/x-raw, format=S16LE, rate=44100, channels=2 ! fdsink fd=3 sync=true 3>&1 1>&2) | nc 127.0.0.1 9999
